import Head from "next/head";
import Image from "next/image";
import Link from "next/link";
import { useEffect, useState } from "react";
import { useRouter } from "next/router";
import Layout from "../components/layout";

export default function Home({ socket }) {
  const router = useRouter();

  useEffect(() => {
    socket.on("createdRoomSuccessfully", (room) => {
      router.push(`/room/${room.users[0].id}`);
    });
  }, []);

  const createRoom = () => {
    socket.emit("createRoom", localStorage.getItem("nickname"));
  };

  return (
    <Layout>
      <Head>
        <title>Sadna Game</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <div className="title">
          <div>Sadna Game</div>
        </div>

        <div>
          <button onClick={() => createRoom()} className="button">
            Create room
          </button>
        </div>
      </main>

      <footer>
        <Link href="/daniel">Go to daniel page</Link>
      </footer>
      <style jsx>{`
        .title {
          font-weight: bold;
          text-align: center;
          font-size: 40px;
        }
        main {
          color: #ffffff;
          height: calc(100vh - 45px);
          background: #353535fa;
          display: flex;
          justify-content: center;
          align-items: center;
          flex-direction: column;
        }
      `}</style>
    </Layout>
  );
}
